### PR TITLE
add lexertl license

### PR DESCRIPTION
**Pull request by remicollet**
parsertl also required, see https://github.com/BenHanson/parsertl14/issues/1

### CODE REVIEW

**Comment by remicollet** [comment]
@weltling can you please sync parsertl to retrieve the missing license file ?

**Comment by weltling** [comment]
@remicollet yeah, will do. Some ext code needs to be adapted yet.

**Comment by remicollet** [comment]
or you can only pull the license file ;)

**Comment by remicollet** [comment]
btw, no urgency, as both lib have same upstream/license

**Comment by weltling** [comment]
Just did it, as i went for it anyway. The code change was simple, should make a closer look yet as there might be some more improvement to pull. Will be delivered in the next tarball then, as i've just pushed one today :) Thanks.

**Pull request merged**
